name: apod
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #chopper: ^4.0.1
  google_fonts: ^2.1.0
  freezed_annotation: ^0.15.0
  intl: ^0.17.0
  provider: ^6.0.1
  json_annotation: ^4.3.0
  uuid: ^3.0.5
  shared_preferences: ^2.0.8
  flutter_colorpicker: ^0.6.0
  go_router: ^2.2.1

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  #chopper_generator: 4.0.1
  freezed: ^0.15.1+1
  json_serializable: ^6.0.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json_files/
    - assets/logo_image/
    - assets/apod_images/
